--SELECT * FROM PR_CREDITO_ADEUDO_TEMP
DECLARE @FEC_REGISTROS DATETIME = GETDATE()
DECLARE @ADEUDO_SIMPLE TABLE  
( 
	COD_CLIENTE VARCHAR(20),
	NUM_CREDITO VARCHAR(20),
	IND_ESTADO VARCHAR(20),
	TIP_RELACION VARCHAR(20),
	IND_ADEUDO_OTROS VARCHAR(20)
);

INSERT INTO @ADEUDO_SIMPLE 
SELECT COD_CLIENTE, NUM_CREDITO, IND_ESTADO, TIP_RELACION, IND_ADEUDA_OTROS FROM PR_CREDITO_ADEUDO_TEMP

INSERT INTO PR_CREDITO_NO_ADEUDO_SIMPLE
SELECT COD_CLIENTE, @FEC_REGISTROS, 'S' FROM @ADEUDO_SIMPLE WHERE IND_ADEUDO_OTROS = 'N'

INSERT INTO PR_CREDITO_NO_ADEUDO_DETA
SELECT @FEC_REGISTROS,COD_CLIENTE,NUM_CREDITO, IND_ESTADO, TIP_RELACION FROM @ADEUDO_SIMPLE WHERE IND_ADEUDO_OTROS = 'S'

SELECT * FROM PR_CREDITO_NO_ADEUDO_SIMPLE
SELECT * FROM PR_CREDITO_NO_ADEUDO_DETA


--DELETE FROM PR_CREDITO_NO_ADEUDO_SIMPLE 
--DELETE FROM PR_CREDITO_NO_ADEUDO_DETA